### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'init_context'

### ISSUE THREAD

**Issue by jhong3842** [alexhude/uEmu#17]
I have to emulate armle, thumb mode in ida 7.3

now i used this plugin, i have a error

Traceback (most recent call last):
  File "C:/Users/JaeHong/Downloads/uEmu-master (1)/uEmu-master/uEmu.py", line 111, in activate
    self.action_handler.handle_menu_action(self.action_type)
  File "C:/Users/JaeHong/Downloads/uEmu-master (1)/uEmu-master/uEmu.py", line 1739, in handle_menu_action
    [x.handler() for x in self.MENU_ITEMS if x.action == action]
  File "C:/Users/JaeHong/Downloads/uEmu-master (1)/uEmu-master/uEmu.py", line 1855, in emu_start
    self.unicornEngine.run_from(IDAAPI_ScreenEA())
  File "C:/Users/JaeHong/Downloads/uEmu-master (1)/uEmu-master/uEmu.py", line 1429, in run_from
    if self.init_cpu_context(address) == False:
  File "C:/Users/JaeHong/Downloads/uEmu-master (1)/uEmu-master/uEmu.py", line 1385, in init_cpu_context
    if self.owner.ext_hooks.init_context is not None:
AttributeError: 'NoneType' object has no attribute 'init_context'

**Comment by alexhude** [comment]
ops, fixed :)
