### ISSUE TITLE
"show memory range" TypeError

### ISSUE THREAD

**Issue by 0xE9DEADBEEF** [alexhude/uEmu#18]
IDA PRO 7.4.191112
Python 3.7.6 x64
Win10

When I try to display memory I've this error :
```
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 111, in activate
    self.action_handler.handle_menu_action(self.action_type)
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1737, in handle_menu_action
    [x.handler() for x in self.MENU_ITEMS if x.action == action]
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1737, in <listcomp>
    [x.handler() for x in self.MENU_ITEMS if x.action == action]
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1993, in show_memory
    self.memoryViews[mem_addr].Create("uEmu Memory [ " + mem_cmnt.encode('utf8') + " ]")
TypeError: can only concatenate str (not "bytes") to str
```

Full context :
```
BinDiff 6 (@297836223, Feb 28 2020), (c)2004-2011 zynamics GmbH, (c)2011-2020 Google LLC.
BinExport 11 (@297836223, Feb 28 2020), (c)2004-2011 zynamics GmbH, (c)2011-2020 Google LLC.

  bytes   pages size description
--------- ----- ---- --------------------------------------------
   942080   115 8192 allocating memory for b-tree...
   548864    67 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
  1753088            total memory allocated

Loading processor module C:\Program Files\IDA Pro 7.4\procs\pc.dll for metapc...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
WARNING: The method "ida_kernwin.UI_Hooks::finish_populating_tform_popup" won't be called (it has been replaced with "ida_kernwin.UI_Hooks::finish_populating_widget_popup")
[uEmu]: Init plugin uEmu
Database for file 'XXXXX.exe' has been loaded.
Hex-Rays Decompiler plugin has been loaded (v7.4.0.191112)
  License: XXXXXXXXXXXXXXXXX (1 user)
  The hotkeys are F5: decompile, Ctrl-F5: decompile all.
  Please check the Edit/Plugins menu for more informaton.
IDAPython Hex-Rays bindings initialized.
================================================================================
WARNING: The method "ida_kernwin.UI_Hooks::finish_populating_tform_popup" won't be called (it has been replaced with "ida_kernwin.UI_Hooks::finish_populating_widget_popup")
[uEmu]: Init plugin uEmu
40BD7A: restored microcode from idb
40D92D: using guessed type int __thiscall WinMain(_DWORD);
420BB0: using guessed type void *off_420BB0;
[uEmu]: UI ready. Run plugin
[uEmu]: Unicorn version [ 1.0.1 ]
[uEmu]: CPU arch set to [ x86 ]
------------------------------------------------------------------------------------------
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] 
IDAPython v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
------------------------------------------------------------------------------------------
[uEmu]: Mapping segments...
[uEmu]: * seg [401000:414000]
[uEmu]:   map [401000:413FFF] -> [401000:413FFF]
[uEmu]:   cpy [401000:413FFF]
[uEmu]: * seg [414000:414408]
[uEmu]:   map [414000:414FFF] -> [414000:414FFF]
[uEmu]:   skp [414000:41400F]
[uEmu]:   cpy [414010:414013]
[uEmu]:   skp [414010:414017]
[uEmu]:   cpy [414018:41401B]
[uEmu]:   skp [414018:41409B]
[uEmu]:   cpy [41409C:41409F]
[uEmu]:   skp [41409C:414207]
[uEmu]:   cpy [414208:41420B]
[uEmu]:   skp [414208:4143CF]
[uEmu]:   cpy [4143D0:4143D3]
[uEmu]:   skp [4143D0:4143F3]
[uEmu]:   cpy [4143F4:4143F7]
[uEmu]:   skp [4143F4:414403]
[uEmu]:   cpy [414404:414407]
[uEmu]: * seg [414408:419000]
[uEmu]:   map [415000:418FFF] -> [415000:418FFF]
[uEmu]:   cpy [414408:418FFF]
[uEmu]: * seg [419000:426000]
[uEmu]:   map [419000:425FFF] -> [419000:425FFF]
[uEmu]:   cpy [419000:42364F]
[uEmu]: Emulation started
[uEmu]: ! <M> Missing memory at 0xfffffffc, data size = 4, data value = 0xf
[uEmu]: ! <C> execute_sync(<function uEmuUnicornEngine.hook_mem_invalid.<locals>.result_handler at 0x000001F0973BF8B8>) failed
[uEmu]: ! <M> Missing memory at 0xfffffffc, data size = 4, data value = 0xf
[uEmu]:   map [FFFFFFFC:FFFFFFFF] -> [FFFFF000:FFFFFFFF]
[uEmu]:   unmap [401000:413FFF]
[uEmu]:   unmap [414000:414FFF]
[uEmu]:   unmap [415000:418FFF]
[uEmu]:   unmap [419000:425FFF]
[uEmu]:   unmap [FFFFF000:FFFFFFFF]
[uEmu]: Emulation reset
[uEmu]: Mapping segments...
[uEmu]: * seg [401000:414000]
[uEmu]:   map [401000:413FFF] -> [401000:413FFF]
[uEmu]:   cpy [401000:413FFF]
[uEmu]: * seg [414000:414408]
[uEmu]:   map [414000:414FFF] -> [414000:414FFF]
[uEmu]:   skp [414000:41400F]
[uEmu]:   cpy [414010:414013]
[uEmu]:   skp [414010:414017]
[uEmu]:   cpy [414018:41401B]
[uEmu]:   skp [414018:41409B]
[uEmu]:   cpy [41409C:41409F]
[uEmu]:   skp [41409C:414207]
[uEmu]:   cpy [414208:41420B]
[uEmu]:   skp [414208:4143CF]
[uEmu]:   cpy [4143D0:4143D3]
[uEmu]:   skp [4143D0:4143F3]
[uEmu]:   cpy [4143F4:4143F7]
[uEmu]:   skp [4143F4:414403]
[uEmu]:   cpy [414404:414407]
[uEmu]: * seg [414408:419000]
[uEmu]:   map [415000:418FFF] -> [415000:418FFF]
[uEmu]:   cpy [414408:418FFF]
[uEmu]: * seg [419000:426000]
[uEmu]:   map [419000:425FFF] -> [419000:425FFF]
[uEmu]:   cpy [419000:42364F]
[uEmu]: Emulation started
[uEmu]: Emulator is already active
[uEmu]: ! <M> Missing memory at 0xfffffffc, data size = 4, data value = 0xf
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 6849, in helper_cb
    r = self.handler(fid)
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1000, in OnFormChange
    self.SetControlValue(self.total_label, "Total: %d (0x%X)" % (size, size))
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 7532, in SetControlValue
    tid, _ = self.ControlToFieldTypeIdAndSize(ctrl)
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 7559, in ControlToFieldTypeIdAndSize
    return (3, min(_ida_kernwin.MAXSTR, ctrl.size))
AttributeError: module '_ida_kernwin' has no attribute 'MAXSTR'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 6849, in helper_cb
    r = self.handler(fid)
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1000, in OnFormChange
    self.SetControlValue(self.total_label, "Total: %d (0x%X)" % (size, size))
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 7532, in SetControlValue
    tid, _ = self.ControlToFieldTypeIdAndSize(ctrl)
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 7559, in ControlToFieldTypeIdAndSize
    return (3, min(_ida_kernwin.MAXSTR, ctrl.size))
AttributeError: module '_ida_kernwin' has no attribute 'MAXSTR'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 6849, in helper_cb
    r = self.handler(fid)
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1000, in OnFormChange
    self.SetControlValue(self.total_label, "Total: %d (0x%X)" % (size, size))
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 7532, in SetControlValue
    tid, _ = self.ControlToFieldTypeIdAndSize(ctrl)
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_kernwin.py", line 7559, in ControlToFieldTypeIdAndSize
    return (3, min(_ida_kernwin.MAXSTR, ctrl.size))
AttributeError: module '_ida_kernwin' has no attribute 'MAXSTR'
[uEmu]:   map [FFFFFFFC:FFFFFFFF] -> [FFFFF000:FFFFFFFF]
[uEmu]: Breakpoint reached at 0x4012F6 : push ebp; bRevert
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 111, in activate
    self.action_handler.handle_menu_action(self.action_type)
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1737, in handle_menu_action
    [x.handler() for x in self.MENU_ITEMS if x.action == action]
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1737, in <listcomp>
    [x.handler() for x in self.MENU_ITEMS if x.action == action]
  File "C:/Program Files/IDA Pro 7.4/plugins/uEmu.py", line 1993, in show_memory
    self.memoryViews[mem_addr].Create("uEmu Memory [ " + mem_cmnt.encode('utf8') + " ]")
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by alexhude** [comment]
Fixed in #066aaf4.

Regarding `_ida_kernwin.MAXSTR` it is a well known IDA python bug. You can define it manually in IDA python or replace with actual value in here **ida_kernwin.py**:
```
7588:    return (3, min(_ida_kernwin.MAXSTR, ctrl.size))
```
