### ISSUE TITLE
OSError: [WinError -1073741795] Windows Error 0xc000001d

### ISSUE THREAD

**Issue by dionysus1231** [alexhude/uEmu#43]
Use this tool with IDA7.7_pro + python3.11.3 under win10_64bit ,Simulate any function ,Encounter the following Err:

E:/IDA_Pro_7.7/plugins/uEmu.py:494: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  return t is not BADSEL and t is not 0
WARNING: The method "ida_kernwin.UI_Hooks::finish_populating_tform_popup" won't be called (it has been replaced with "ida_kernwin.UI_Hooks::finish_populating_widget_popup")
[uEmu]: Init plugin uEmu
IDA is analysing the input file...
You may start to explore the input file right now.
[uEmu]: UI ready. Run plugin
[uEmu]: Unicorn version [ 2.0.1 ]
[uEmu]: CPU arch set to [ armle ]
[Patching] Loaded v0.1.2 - (c) Markus Gaasedelen - 2022
-----------------------------------------------------------------------------------------
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] 
IDAPython v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
-----------------------------------------------------------------------------------------
Propagating type information...
Function argument information has been propagated
The initial autoanalysis has been finished.
  File "E:/IDA_Pro_7.7/plugins/uEmu.py", line 110, in activate
    if ctx.form_type == BWN_DISASM:
Please use "widget_type" instead of "form_type" ("form_type" is kept for backward-compatibility, and will be removed soon.)
[uEmu]: VFP enabled
[uEmu]: Mapping segments...
[uEmu]: * seg [0:174]
[uEmu]:   map [0:FFF] -> [0:FFF]
[uEmu]:   cpy [0:173]
[uEmu]: * seg [174:4EEE4C]
[uEmu]:   map [1000:4EEFFF] -> [1000:4EEFFF]
[uEmu]:   cpy [174:4EEE4B]
[uEmu]: * seg [4EEE4C:51557C]
[uEmu]:   map [4EF000:515FFF] -> [4EF000:515FFF]
[uEmu]:   cpy [4EEE4C:51557B]
[uEmu]: * seg [51557C:531A3C]
[uEmu]:   map [516000:531FFF] -> [516000:531FFF]
[uEmu]:   cpy [51557C:531A3B]
[uEmu]: * seg [531A3C:5BC000]
[uEmu]:   map [532000:5BBFFF] -> [532000:5BBFFF]
[uEmu]:   cpy [531A3C:5BBFFF]
[uEmu]: * seg [5BC000:63A000]
[uEmu]:   map [5BC000:639FFF] -> [5BC000:639FFF]
[uEmu]: * seg [63A000:63A008]
[uEmu]:   map [63A000:63AFFF] -> [63A000:63AFFF]
[uEmu]:   cpy [63A000:63A007]
[uEmu]: * seg [63A008:63A01C]
[uEmu]:   cpy [63A008:63A01B]
[uEmu]: * seg [63A01C:63A02C]
[uEmu]:   cpy [63A01C:63A02B]
[uEmu]: * seg [63A02C:6487F8]
[uEmu]:   map [63B000:648FFF] -> [63B000:648FFF]
[uEmu]:   cpy [63A02C:6487F7]
[uEmu]: * seg [649D9C:64B77C]
[uEmu]:   map [649D9C:64BFFF] -> [649000:64BFFF]
[uEmu]:   cpy [649D9C:64B77B]
[uEmu]: * seg [64B77C:7A2578]
[uEmu]:   map [64C000:7A2FFF] -> [64C000:7A2FFF]
[uEmu]:   cpy [64B77C:7A2577]
[uEmu]: * seg [7A2578:80FF54]
[uEmu]:   map [7A3000:80FFFF] -> [7A3000:80FFFF]
[uEmu]:   cpy [7A2578:80FF53]
[uEmu]: * seg [80FF54:810098]
[uEmu]:   map [810000:810FFF] -> [810000:810FFF]
[uEmu]:   cpy [80FF54:810097]
[uEmu]: Emulation started
Exception in thread Thread-1 (step_thread_main):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "E:/IDA_Pro_7.7/plugins/uEmu.py", line 1508, in step_thread_main
    self.mu.emu_start(self.pc | 1 if UEMU_HELPERS.is_thumb_ea(self.pc) else self.pc, -1, count=1)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\unicorn\unicorn.py", line 545, in emu_start
    status = _uc.uc_emu_start(self._uch, begin, until, timeout, count)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -1073741795] Windows Error 0xc000001d

Have tested on win7_64bit, different version of python,Same issue.

**Comment by dionysus1231** [comment]
Recompile the source code on the target OS, replace the dll file, everything is OK!
